### ISSUE TITLE
No IPv4 address found on vboxnet

### ISSUE THREAD

**Issue by hectorv** [guedou/scapy-bpf#2]
Hi,
I installed this version of scapy using pip:
```
$ pip install git+git://github.com/guedou/scapy-bpf.git
```

but then I got this exception:
```
$ scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
ifconfig: interface vboxnet does not exist
Traceback (most recent call last):
  File "/Users/hector/.virtualenvs/duo/bin/scapy", line 25, in <module>
    interact()
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/main.py", line 278, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/all.py", line 25, in <module>
    from route import *
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/route.py", line 162, in <module>
    conf.route=Route()
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/route.py", line 22, in __init__
    self.resync()
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/arch/unix.py", line 81, in read_routes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/arch/__init__.py", line 44, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
  File "/Users/hector/.virtualenvs/duo/lib/python2.7/site-packages/scapy/arch/bpf.py", line 83, in get_if_raw_addr
    raise Scapy_Exception("No IPv4 address found on %s !" % ifname)
scapy.error.Scapy_Exception: No IPv4 address found on vboxnet !
```

which I guess makes sense because I don't have a `vboxnet` interface:
```
$ ifconfig -l
lo0 gif0 stf0 en0 p2p0 awdl0 en1 bridge0 vboxnet0 vboxnet1 ppp0
```

is there a workaround to this issue? Thanks!

**Comment by guedou** [comment]
Thanks for your interest in this native port !

This is a known Scapy bug that will be fixed in [PR 149](https://github.com/secdev/scapy/pull/149).
I won't fix it in this repository, as it will likely make the BPF patch harder to merge. I will do my best to merge PR 149 ASAP, and push scapy-bpg upstreeam.

In the mean time, I will suggest that you patch unix.py:81 your self using something like:
```python
if not "vboxnet" not in netif:
            ifaddr = scapy.arch.get_if_addr(netif)
            routes.append((dest,netmask,gw,netif,ifaddr))
```
